# Generated by Django 4.2.9 on 2024-10-23 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0060_delete_dumpurl"),
    ]

    operations = [
        migrations.CreateModel(
            name="DumpUrl",
            fields=[
                (
                    "url_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sde_collections.url",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dump URL",
                "verbose_name_plural": "Dump URLs",
            },
            bases=("sde_collections.url",),
        ),
    ]
