# Generated by Django 4.2.9 on 2024-11-11 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sde_collections", "0062_deltatitlepattern_deltaresolvedtitleerror_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curatedurl",
            options={"ordering": ["url"], "verbose_name": "Curated Urls", "verbose_name_plural": "Curated Urls"},
        ),
        migrations.AlterModelOptions(
            name="deltadivisionpattern",
            options={"verbose_name": "Delta Division Pattern", "verbose_name_plural": "Delta Division Patterns"},
        ),
        migrations.AlterModelOptions(
            name="deltadocumenttypepattern",
            options={
                "verbose_name": "Delta Document Type Pattern",
                "verbose_name_plural": "Delta Document Type Patterns",
            },
        ),
        migrations.AlterModelOptions(
            name="deltaexcludepattern",
            options={"verbose_name": "Delta Exclude Pattern", "verbose_name_plural": "Delta Exclude Patterns"},
        ),
        migrations.AlterModelOptions(
            name="deltaincludepattern",
            options={"verbose_name": "Delta Include Pattern", "verbose_name_plural": "Delta Include Patterns"},
        ),
        migrations.AlterModelOptions(
            name="deltatitlepattern",
            options={"verbose_name": "Delta Title Pattern", "verbose_name_plural": "Delta Title Patterns"},
        ),
        migrations.AlterModelOptions(
            name="deltaurl",
            options={"ordering": ["url"], "verbose_name": "Delta Urls", "verbose_name_plural": "Delta Urls"},
        ),
        migrations.AlterModelOptions(
            name="dumpurl",
            options={"ordering": ["url"], "verbose_name": "Dump Urls", "verbose_name_plural": "Dump Urls"},
        ),
    ]
